### ISSUE TITLE
Header links are broken with JS off, misbehave with JS on

### ISSUE THREAD

**Issue by nyanpasu64** [resir014/thebestmotherfuckingwebsite.co#6]
The header links (About, Features, and Epilogue) do not work when JS is disabled.

With JS enabled, clicking those links begins a 1-second animation where the page scrolls down. If you alt-tab out of the page, the page stops scrolling before reaching the destination. I think jumping to an `#anchor` URL would be better than reimplementing that functionality in JS.

Also I generally dislike floating headers.

Also the View Source is unreadable since everything is minified and squished into long lines. I heard in the past, people learned web design by reading HTML (which can't happen with this site). At least Inspect Element is still readable.

In the past, it made Firefox's CSS/JS "jump to source" always jump to line 1 or so, rather than the true location of the code. (IDK if they fixed it yet.) Is Chrome's "jump to source" better at dealing with minified resources?

**Comment by resir014** [comment]
> In the past, it made Firefox's CSS/JS "jump to source" always jump to line 1 or so, rather than the true location of the code. (IDK if they fixed it yet.) Is Chrome's "jump to source" better at dealing with minified resources?

@jimbo1qaz Chrome supports pretty-printing minified code on both CSS and JS which makes jump to source much readable. Though not sure this works on inline scripts/styles.

![image](https://user-images.githubusercontent.com/5663877/72770300-0482d000-3c30-11ea-996c-302b35f61171.png)

![image](https://user-images.githubusercontent.com/5663877/72770169-a1913900-3c2f-11ea-85d7-4e18de8be00f.png)

Agree with using anchor links for header though. I only use the library I'm currently using for "scroll spy", applying certain CSS classes (e.g. in the header) when you scroll a certain point, and nothing more. I'll look into it when I have the time.

**Comment by resir014** [comment]
@jimbo1qaz 

> I heard in the past, people learned web design by reading HTML (which can't happen with this site).

Keyword: the past.

Nowadays, modern JavaScript bundlers include [source maps](https://blog.teamtreehouse.com/introduction-source-maps), which allows parts of the source code visible on the page to be viewable by Inspect Element.

Example in Chrome:

![image](https://user-images.githubusercontent.com/5663877/73138721-9491a100-4098-11ea-8c1c-4abf07848136.png)

This means you can still debug the full JavaScript without sacrificing performance by keeping minified JS.
